sudo: required
services:
  - docker
language: node_js
node_js:
  - "node"
branches:
  only:
    - production
    - development
install:
  - npm install
script:
  - npm run-script lint
  - npm run-script build
after_success:
  - docker build -t misticwonder/awix-api-$TRAVIS_BRANCH .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $DOCKER_USERNAME/awix-api-$TRAVIS_BRANCH;
