version: "3"
services:
  postgres:
    image: "misticwonder/postgres"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - ~/server/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
